### PR TITLE
Add Fmax to viz.error_table (used in the same way as fit.fit())

### LINKED ISSUE #24: Excluding large forces from training / test error reports
Occasionally the trian/test errors can look strange if a large force component greater than 'Fmax' is included in the train/test database. This can skew the error table considerably, while the actual model itself typically runs very well and has good generalisation on 'normal' forces. 

@bernstei What are your thoughts on excluding these forces (and perhaps the total energy too) from training and test? It has confused me and I'm sure it may do so for others too.

### PR DESCRIPTION
**Pull request by bernstei**
Also, print a summary of Fmax-related exclusions (# of configs E & V and # of individual atom forces) when building the design matrix for fitting.

closes #24

### CODE REVIEW

**Comment by bernstei** [comment]
@casv2 Can you look at this carefully and see if it does what you think it should?

**Comment by casv2** [comment]
Yes I think this looks great, I see you're also dropping the virials if F > Fmax which indeed is the right thing to do.

**Comment by casv2** [comment]
Great, this prints during fitting which is when I think we want to inform users.

**Comment by bernstei** [comment]
Are we ready to merge?

**Pull request merged**
